# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_m <- function(n) {
    .Call(`_NMLmulti_sample_m`, n)
}

reject <- function(n) {
    .Call(`_NMLmulti_reject`, n)
}

gibbs <- function(n, ks) {
    .Call(`_NMLmulti_gibbs`, n, ks)
}

burnin <- function(burn, init, ks, Ns) {
    .Call(`_NMLmulti_burnin`, burn, init, ks, Ns)
}

gen_chain <- function(ks, Ns, batchsize, thin, startvec) {
    .Call(`_NMLmulti_gen_chain`, ks, Ns, batchsize, thin, startvec)
}

SCR <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_SCR`, Q0, chd, NN)
}

LT <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_LT`, Q0, chd, NN)
}

SCR_V <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_SCR_V`, Q0, chd, NN)
}

SCR_G <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_SCR_G`, Q0, chd, NN)
}

ifmu <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_ifmu`, Q0, chd, NN)
}

ufmu <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_ufmu`, Q0, chd, NN)
}

qm <- function(Q0, chd, NN) {
    .Call(`_NMLmulti_qm`, Q0, chd, NN)
}

